import { defineConfig } from 'astro/config';
import react from '@astrojs/react';
import keystatic from '@keystatic/astro';
import netlify from '@astrojs/netlify';
import rehypeAffiliate from './src/lib/affiliate-rehype.mjs';

// French Riviera Tips — Astro config
// Static site (SSG) + a small server island for Keystatic admin.
// Sitemap is generated by src/pages/sitemap.xml.js (custom, avoids the
// @astrojs/sitemap hybrid-output bug).
export default defineConfig({
  site: 'https://www.frenchrivieratips.com',
  output: 'hybrid',
  adapter: netlify(),
  integrations: [
    react(),
    keystatic(),
  ],
  markdown: {
    // Add rel="sponsored nofollow" + target=_blank to affiliate/external links at build.
    rehypePlugins: [rehypeAffiliate],
  },
});
